### ISSUE TITLE
请问软件该如何使用

### ISSUE THREAD

**Issue by BasaltCompass** [Zhoucheng133/CuteHttpFileServer-GUI#1]
作者你好，我阅读了readme文件，其中提及下载原始程序后再使用您的gui。可我看realease是空的，在主页中也没有找到windows可运行的部分（我只是电脑小白的水平）。

请问您的gui软件该如何使用？

（ps我之前使用的是官网上chfs2.0的gui，遇到了webdav只能识别第一个加载的目录的bug；转而学习使用chfs3.1命令行，在设置用户权限方面又遇到了困难；之后就发现了活跃时间较近的您的项目）

**Comment by Zhoucheng133** [comment]
啊不好意思，前几天从Gitee把我的项目转移过来，忘了发布Relase了，稍后补上

**Comment by Zhoucheng133** [comment]
我看到你是要在Windows系统上使用对吧，那真的很抱歉，因为官网有Windows系统的GUI版本，而我使用的是Mac，所以当初开发的初衷是给Mac或者Linux系统做一个GUI界面的，因此我目前既没有在Windows系统上开发的环境也没有对Windows系统做适配，如果你发现了官方的GUI版本有任何问题，建议你联系官方chfs的作者：

> docblue@163.com

关于Windows命令行版本的使用，你可以[点击这里](http://iscute.cn/chfs)参考官方网站

关于Windows系统的权限问题，由于这个项目也只是自动执行命令，所以我想即便我开发了适配Windows版本的软件很有可能依然无法正确地在你设备上运行

另外如果你需要寻找一个分享文件的软件，你可以试试我的另外一个开源项目：
[Virtual Directory](https://github.com/Zhoucheng133/virtual-directory#virtual-directory)

感谢你的留言
